#if !canImport(ObjectiveC)
import XCTest

extension HTTPClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPClientTests = [
        ("testExampleCom", testExampleCom),
        ("testGoogleAPIsFCM", testGoogleAPIsFCM),
        ("testGoogleWithTLS", testGoogleWithTLS),
        ("testHTTPBin418", testHTTPBin418),
        ("testHTTPBinAnything", testHTTPBinAnything),
        ("testHTTPBinRobots", testHTTPBinRobots),
        ("testQuery", testQuery),
        ("testSNIWebsite", testSNIWebsite),
        ("testVaporWithTLS", testVaporWithTLS),
        ("testZombo", testZombo),
    ]
}

extension HTTPTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTTPTests = [
        ("testAcceptHeader", testAcceptHeader),
        ("testClientDefaultConfig", testClientDefaultConfig),
        ("testClientProxyPlaintext", testClientProxyPlaintext),
        ("testClientProxyTLS", testClientProxyTLS),
        ("testCookieIsSerializedCorrectly", testCookieIsSerializedCorrectly),
        ("testCookieParse", testCookieParse),
        ("testLargeResponseClose", testLargeResponseClose),
        ("testMultipleCookiesAreSerializedCorrectly", testMultipleCookiesAreSerializedCorrectly),
        ("testRemotePeer", testRemotePeer),
        ("testRFC1123Flip", testRFC1123Flip),
        ("testUncleanShutdown", testUncleanShutdown),
    ]
}

extension WebSocketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebSocketTests = [
        ("testClient", testClient),
        ("testClientTLS", testClientTLS),
        ("testServer", testServer),
        ("testServerContinuation", testServerContinuation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTTPClientTests.__allTests__HTTPClientTests),
        testCase(HTTPTests.__allTests__HTTPTests),
        testCase(WebSocketTests.__allTests__WebSocketTests),
    ]
}
#endif
